# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 575542ec81a578c80196c31fd5cbb456c573f8b9662692c733b9301017b3892d23d763fd38ca2d196b232eb29db1905c65cdddb20f50cd717671265cd80d8f9e

test:
  secret_key_base: 43b239d46c347644e354eb5be29ce1a80d4a7e2b056f7cfaa847dec2fba88fee2e54cb5e538a314405d8b3b9eead139131d3604caa25ffc9e9ce180dd703226b

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
